# Generated by Django 4.0.6 on 2022-07-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name_plural': 'Application Email'},
        ),
        migrations.AlterModelOptions(
            name='responsibility',
            options={'verbose_name_plural': 'Responsibilities'},
        ),
    ]
