# Generated by Django 4.0.6 on 2022-07-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_email_options_alter_responsibility_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='type',
            field=models.CharField(choices=[('Full-Time', 'Full-time'), ('Part-Time', 'Part-time')], default='Part-Time', max_length=10),
        ),
    ]
