# Generated by Django 4.0.6 on 2022-07-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_service', models.CharField(choices=[('GD', 'Graphic Design'), ('MG', 'Motion Graphics')], max_length=2)),
                ('service_text', models.TextField()),
                ('service_cover_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
