# Generated by Django 4.0.6 on 2022-07-22 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_name_of_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='name_of_service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_cover_image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_text',
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='hello', max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'verbose_name_plural': 'Service Details',
            },
        ),
    ]
