# Generated by Django 4.0.6 on 2022-07-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentcreatives', '0002_project_video_sketch_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sketch',
            name='project',
        ),
        migrations.RemoveField(
            model_name='video',
            name='project',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Sketch',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
