# Generated by Django 4.0.6 on 2022-07-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_program_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(),
        ),
    ]
